create table VISITOR
(
  VISIT_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  VISIT_ID VARCHAR(100),
  VISIT_IP VARCHAR(100),
  VISIT_ADDR VARCHAR(100),
  VISIT_TIME VARCHAR(100),
  VISIT_REFER VARCHAR(100),
  VISIT_AGENT VARCHAR(600),
  PRODUCT VARCHAR(100),
  PRODUCT_V VARCHAR(100),
  SYSTEM VARCHAR(100),
  SYSTEM_V VARCHAR(100),
  PLATFORM VARCHAR(100),
  PLATFORM_V VARCHAR(100),
  EXT VARCHAR(100),
 PRIMARY KEY(VISIT_SEQ)
);

